/* =========================================================
   Dados extraídos do site antigo (script.js + dados/produtos.js).
   Gerado automaticamente na migração — não edite à mão.

   ⚠️ IMPORTANTE: peso e dimensões aqui são ESTIMATIVAS herdadas
   do projeto antigo (vários tinham "TODO: COLOCAR_PESO_AQUI").
   Todos entram no banco com medidasVerificadas = false e
   aparecem destacados no painel até serem conferidos.
   ========================================================= */

export type ProdutoLegado = {
  idAntigo: number;
  nome: string;
  categoria: string;
  descricao: string;
  precoTexto: string;
  badge: string;
  imagens: string[];
  peso: number;
  largura: number;
  altura: number;
  comprimento: number;
  valorDeclarado: number | null;
};

export const CATEGORIAS_LEGADO = [
  { nome: "Buquês", slug: "buques", titulo: "Buquês", subtitulo: "Arranjos artesanais feitos à mão", aliases: [] as string[], ordem: 0 },
  { nome: "Unitários", slug: "unitarios", titulo: "Unitários", subtitulo: "Flores individuais e peças decorativas", aliases: [], ordem: 1 },
  { nome: "Chaveiros", slug: "chaveiros", titulo: "Chaveiros", subtitulo: "Peças pequenas para o dia a dia", aliases: [], ordem: 2 },
  { nome: "Presentes Personalizados", slug: "presentes-personalizados", titulo: "Presentes Personalizados", subtitulo: "Composições sob medida", aliases: ["Presentes"], ordem: 3 },
];

export const PRODUTOS_LEGADO: ProdutoLegado[] = [
  {
    idAntigo: 1,
    nome: "Buquê com 6 Girassóis e 13 Margaridas",
    categoria: "Buquês",
    descricao: "Buquê artesanal delicado com rosas eternas, perfeito para presentear com elegância.",
    precoTexto: "R$ 185,00",
    badge: "",
    imagens: ["imagens/Buquê com 6 Girassóis e 13 Margaridas.png"],
    peso: 0.7,
    largura: 22,
    altura: 45,
    comprimento: 22,
    valorDeclarado: 185,
  },
  {
    idAntigo: 2,
    nome: "Buquê de Lírios",
    categoria: "Buquês",
    descricao: "Buquê composto por 4 lírios realistas e margaridas eternas, ideal para ocasiões especiais.",
    precoTexto: "R$ 145,00",
    badge: "",
    imagens: ["imagens/buquê de Lírios.png"],
    peso: 0.6,
    largura: 22,
    altura: 42,
    comprimento: 22,
    valorDeclarado: 145,
  },
  {
    idAntigo: 3,
    nome: "Buquê Jardim",
    categoria: "Buquês",
    descricao: "Buquê composto por 1 lírio, 1 rosa, 1 dália, 1 margarida e mini margaridinhas, reunindo diferentes flores em uma composição cheia de detalhes e personalidade, (cor do buquê é opcional)",
    precoTexto: "R$ 125,00",
    badge: "",
    imagens: ["imagens/Buquê Jardim.png"],
    peso: 0.6,
    largura: 20,
    altura: 40,
    comprimento: 20,
    valorDeclarado: 125,
  },
  {
    idAntigo: 4,
    nome: "Buquê Lírio do Campo",
    categoria: "Buquês",
    descricao: "Buquê com 1 lírio na cor de sua escolha, acompanhado de 4 mini margaridas e folhagens delicadas, formando uma combinação perfeita.",
    precoTexto: "R$ 58,00",
    badge: "",
    imagens: ["imagens/Buquê Lirio do Campo var 1.png", "imagens/Buquê Lirio do Campo var 2.png", "imagens/Buquê Lirio do Campo var 3.png", "imagens/Buquê Lirio do Campo var 4.png"],
    peso: 0.4,
    largura: 18,
    altura: 35,
    comprimento: 18,
    valorDeclarado: 58,
  },
  {
    idAntigo: 5,
    nome: "Buquê de 3 Girassóis",
    categoria: "Buquês",
    descricao: "Buquê composto por 3 girassóis, margaridas e folhagens.",
    precoTexto: "R$ 75,00",
    badge: "",
    imagens: ["imagens/Buquê de 3 Girassóis.png"],
    peso: 0.5,
    largura: 20,
    altura: 38,
    comprimento: 20,
    valorDeclarado: 75,
  },
  {
    idAntigo: 6,
    nome: "Buquê de 2 Girassóis",
    categoria: "Buquês",
    descricao: "Buquê composto por 2 girassóis, um trio de mini margaridas e folhagens.",
    precoTexto: "R$ 62,00",
    badge: "",
    imagens: ["imagens/Buquê de 2 Girassóis.png"],
    peso: 0.45,
    largura: 18,
    altura: 36,
    comprimento: 18,
    valorDeclarado: 62,
  },
  {
    idAntigo: 7,
    nome: "Buquê Bella",
    categoria: "Buquês",
    descricao: "Buquê composto por 1 lírio central, margaridas ao redor e embrulho premium.",
    precoTexto: "R$ 128,00",
    badge: "",
    imagens: ["imagens/Buquê Bella var1.png", "imagens/Buquê Bella var2.png"],
    peso: 0.6,
    largura: 20,
    altura: 40,
    comprimento: 20,
    valorDeclarado: 128,
  },
  {
    idAntigo: 8,
    nome: "Buquê Lilly",
    categoria: "Buquês",
    descricao: "Buquê composto por 6 lírios na cor de sua preferência e margaridas, em um modelo redondo.",
    precoTexto: "R$ 210,00",
    badge: "",
    imagens: ["imagens/Buquê Lilly var1.png", "imagens/Buquê Lilly var2.png"],
    peso: 0.8,
    largura: 24,
    altura: 46,
    comprimento: 24,
    valorDeclarado: 210,
  },
  {
    idAntigo: 28,
    nome: "Luminária da Rapunzel",
    categoria: "Unitários",
    descricao: "Luminária da Rapunzel com aproximadamente 30cm, decorada com margaridas e fio de fada iluminado. Um item encantador para deixar qualquer cantinho ainda mais especial.",
    precoTexto: "R$ 90,00",
    badge: "Mais vendido",
    imagens: ["imagens/Luminária da Rapunzel.png"],
    peso: 0.5,
    largura: 16,
    altura: 35,
    comprimento: 16,
    valorDeclarado: 90,
  },
  {
    idAntigo: 9,
    nome: "Flor Girassol Artesanal",
    categoria: "Unitários",
    descricao: "Girassol feito à mão para decoração, lembrança ou presente.",
    precoTexto: "R$ 26,90",
    badge: "",
    imagens: ["imagens/flor2.svg"],
    peso: 0.15,
    largura: 14,
    altura: 22,
    comprimento: 10,
    valorDeclarado: 26.9,
  },
  {
    idAntigo: 10,
    nome: "Flor Tulipa Delicada",
    categoria: "Unitários",
    descricao: "Tulipa artesanal em visual suave, feminino e elegante.",
    precoTexto: "R$ 22,90",
    badge: "Novo",
    imagens: ["imagens/flor3.svg"],
    peso: 0.15,
    largura: 14,
    altura: 22,
    comprimento: 10,
    valorDeclarado: 22.9,
  },
  {
    idAntigo: 11,
    nome: "Flor Lavanda Charmosa",
    categoria: "Unitários",
    descricao: "Flor delicada em tons de lavanda para compor arranjos especiais.",
    precoTexto: "R$ 21,90",
    badge: "",
    imagens: ["imagens/flor4.svg"],
    peso: 0.15,
    largura: 14,
    altura: 22,
    comprimento: 10,
    valorDeclarado: 21.9,
  },
  {
    idAntigo: 12,
    nome: "Flor Margarida Branca",
    categoria: "Unitários",
    descricao: "Margarida artesanal leve, minimalista e cheia de charme.",
    precoTexto: "R$ 19,90",
    badge: "Promoção",
    imagens: ["imagens/flor5.svg"],
    peso: 0.15,
    largura: 14,
    altura: 22,
    comprimento: 10,
    valorDeclarado: 19.9,
  },
  {
    idAntigo: 13,
    nome: "Flor Camélia Rosa",
    categoria: "Unitários",
    descricao: "Peça artesanal elegante para presentear ou decorar ambientes.",
    precoTexto: "R$ 27,90",
    badge: "",
    imagens: ["imagens/flor6.svg"],
    peso: 0.15,
    largura: 14,
    altura: 22,
    comprimento: 10,
    valorDeclarado: 27.9,
  },
  {
    idAntigo: 14,
    nome: "Flor Orquídea Lilás",
    categoria: "Unitários",
    descricao: "Flor premium com visual sofisticado e acabamento artesanal.",
    precoTexto: "R$ 34,90",
    badge: "Novo",
    imagens: ["imagens/flor7.svg"],
    peso: 0.15,
    largura: 14,
    altura: 22,
    comprimento: 10,
    valorDeclarado: 34.9,
  },
  {
    idAntigo: 15,
    nome: "Chaveiro Flor de Girassol",
    categoria: "Chaveiros",
    descricao: "Chaveiro artesanal exclusivo, delicado e cheio de personalidade.",
    precoTexto: "R$ 29,90",
    badge: "Mais vendido",
    imagens: ["imagens/chaveiro1.svg"],
    peso: 0.08,
    largura: 12,
    altura: 15,
    comprimento: 5,
    valorDeclarado: 29.9,
  },
  {
    idAntigo: 16,
    nome: "Chaveiro Rosa Lilás",
    categoria: "Chaveiros",
    descricao: "Modelo romântico em tons de lilás, ideal para uso diário.",
    precoTexto: "R$ 27,90",
    badge: "",
    imagens: ["imagens/chaveiro2.svg"],
    peso: 0.08,
    largura: 12,
    altura: 15,
    comprimento: 5,
    valorDeclarado: 27.9,
  },
  {
    idAntigo: 17,
    nome: "Chaveiro Mini Buquê",
    categoria: "Chaveiros",
    descricao: "Mini buquê artesanal em formato de chaveiro para presente criativo.",
    precoTexto: "R$ 32,90",
    badge: "Novo",
    imagens: ["imagens/chaveiro3.svg"],
    peso: 0.08,
    largura: 12,
    altura: 15,
    comprimento: 5,
    valorDeclarado: 32.9,
  },
  {
    idAntigo: 18,
    nome: "Chaveiro Margarida",
    categoria: "Chaveiros",
    descricao: "Peça leve, delicada e artesanal para bolsas, mochilas e chaves.",
    precoTexto: "R$ 24,90",
    badge: "Promoção",
    imagens: ["imagens/chaveiro4.svg"],
    peso: 0.08,
    largura: 12,
    altura: 15,
    comprimento: 5,
    valorDeclarado: 24.9,
  },
  {
    idAntigo: 19,
    nome: "Chaveiro Coração Floral",
    categoria: "Chaveiros",
    descricao: "Chaveiro com tema floral e toque romântico para presentear.",
    precoTexto: "R$ 34,90",
    badge: "",
    imagens: ["imagens/chaveiro5.svg"],
    peso: 0.08,
    largura: 12,
    altura: 15,
    comprimento: 5,
    valorDeclarado: 34.9,
  },
  {
    idAntigo: 20,
    nome: "Chaveiro Tulipa Rosé",
    categoria: "Chaveiros",
    descricao: "Tulipa artesanal charmosa com acabamento em tons suaves.",
    precoTexto: "R$ 28,90",
    badge: "",
    imagens: ["imagens/chaveiro6.svg"],
    peso: 0.08,
    largura: 12,
    altura: 15,
    comprimento: 5,
    valorDeclarado: 28.9,
  },
  {
    idAntigo: 21,
    nome: "Chaveiro Jardim Encantado",
    categoria: "Chaveiros",
    descricao: "Modelo especial com composição floral delicada e premium.",
    precoTexto: "R$ 39,90",
    badge: "Novo",
    imagens: ["imagens/chaveiro7.svg"],
    peso: 0.08,
    largura: 12,
    altura: 15,
    comprimento: 5,
    valorDeclarado: 39.9,
  },
  {
    idAntigo: 22,
    nome: "Caixa Floral Personalizada",
    categoria: "Presentes Personalizados",
    descricao: "Caixa especial com flores artesanais e detalhe personalizado.",
    precoTexto: "R$ 119,90",
    badge: "Mais vendido",
    imagens: ["imagens/presente1.svg"],
    peso: 0.6,
    largura: 25,
    altura: 20,
    comprimento: 20,
    valorDeclarado: 119.9,
  },
  {
    idAntigo: 23,
    nome: "Kit Presente Romântico",
    categoria: "Presentes Personalizados",
    descricao: "Composição personalizada para datas especiais e momentos únicos.",
    precoTexto: "R$ 149,90",
    badge: "Novo",
    imagens: ["imagens/presente2.svg"],
    peso: 0.7,
    largura: 28,
    altura: 20,
    comprimento: 20,
    valorDeclarado: 149.9,
  },
  {
    idAntigo: 24,
    nome: "Mini Arranjo com Nome",
    categoria: "Presentes Personalizados",
    descricao: "Arranjo artesanal com personalização para tornar o presente exclusivo.",
    precoTexto: "R$ 69,90",
    badge: "",
    imagens: ["imagens/presente3.svg"],
    peso: 0.4,
    largura: 20,
    altura: 18,
    comprimento: 18,
    valorDeclarado: 69.9,
  },
  {
    idAntigo: 25,
    nome: "Cesta Jardim das Flores",
    categoria: "Presentes Personalizados",
    descricao: "Cesta elegante com flores eternas e acabamento delicado.",
    precoTexto: "R$ 169,90",
    badge: "Promoção",
    imagens: ["imagens/presente4.svg"],
    peso: 0.9,
    largura: 30,
    altura: 25,
    comprimento: 25,
    valorDeclarado: 169.9,
  },
  {
    idAntigo: 26,
    nome: "Cartão Floral Artesanal",
    categoria: "Presentes Personalizados",
    descricao: "Cartão com detalhe floral artesanal para acompanhar presentes.",
    precoTexto: "R$ 39,90",
    badge: "",
    imagens: ["imagens/presente5.svg"],
    peso: 0.1,
    largura: 18,
    altura: 13,
    comprimento: 2,
    valorDeclarado: 39.9,
  },
  {
    idAntigo: 27,
    nome: "Presente Premium Sob Encomenda",
    categoria: "Presentes Personalizados",
    descricao: "Produto personalizado conforme ocasião, cores e estilo desejados.",
    precoTexto: "A consultar",
    badge: "Novo",
    imagens: ["imagens/presente6.svg"],
    peso: 0.3,
    largura: 15,
    altura: 10,
    comprimento: 12,
    valorDeclarado: null,
  },
];
